install: game.cpp ./TinyXML/tinyxml.cpp ./TinyXML/tinystr.cpp ./TinyXML/tinyxmlerror.cpp ./TinyXML/tinyxmlparser.cpp ./Instance.cpp ./Move.cpp ./Room.cpp
	g++ game.cpp ./TinyXML/tinyxml.cpp ./TinyXML/tinystr.cpp ./TinyXML/tinyxmlerror.cpp ./TinyXML/tinyxmlparser.cpp ./Instance.cpp ./Move.cpp ./Room.cpp -o game --std=c++11
